### ISSUE TITLE
Cannot right-click apps in the system tray area if auto-hide taskbar is enabled

### ISSUE THREAD

**Issue by xcloudx01** [CrypticButter/ButteryTaskbar#16] opened 2022-09-21 05:24 UTC
OS: Windows 11 Pro
OS Build: 22622.590
Buttery Taskbar: 1.2.2.1

Problem behavior:
When right-clicking a program in the windows tray icon area, the taskbar hides and the right-click menu does not appear.

Expected behavior:
Right-click a program in the windows tray icon area and access its right-click menu.

Additional notes:
It only occurs when window's "Automatically hide the taskbar" is set to ON.
The bug is semi-random, occasionally it will open the right-click menu, but most of the time it will not.
However running with Auto-hide the taskbar off and letting Buttery Taskbar handle it, it hides the taskbar but i cannot resize any windows beyond where the taskbar usually sits.

**Comment by xcloudx01** [comment] 2022-09-21 05:31
https://user-images.githubusercontent.com/18512288/191421813-0bc042c4-92b3-4ba7-9426-3a059a9d7448.mp4

Here's a video of the issue. You can see that after turning on Automatically hide the taskbar, right-clicking items in the tray area no longer always opens the menu. Sometimes the taskbar just dissapears and that's it. From my fiddling around with it, it seems to effect pretty much all apps.

**Comment by LuisThiamNye** [comment] 2022-09-21 07:51
This is a duplicate of #12

I think you have already reported this in issue #15

**Closed as not planned** 2022-09-21 07:52 UTC
Labels: duplicate
