### ISSUE TITLE
Unable to right-click an icon in the tray area.

### ISSUE THREAD

**Issue by xcloudx01** [CrypticButter/ButteryTaskbar#15] opened 2022-04-20 15:38 UTC
When using Buttery Taskbar, if I press the Windows key to open up the taskbar, and then I right-click a tray icon in the lower right to open its menu, the taskbar will close and the programs right-click menu will not open about 80% of the time. If I just repeatedly try, it will eventually work, but I have to try many times.

**Comment by LuisThiamNye** [comment] 2022-04-20 16:21
This is a duplicate of #12

In theory it could be worked around, but I no longer work on this project.

**Closed as completed by LuisThiamNye** 2022-04-20 16:21 UTC
Labels: duplicate
